DATABASE_USERNAME = 'sunil'
DATABASE_PASSWORD = 'password'
DATABASE_NAME     = 'indii_2_0_contracts'
SQLALCHEMY_DATABASE_URI = f'postgresql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@localhost/{DATABASE_NAME}'
