import os

DATABASE_HOST = os.environ.get("DB_HOST")
DATABASE_USERNAME = os.environ.get("DB_USER")
DATABASE_PASSWORD = os.environ.get("DB_PASSWORD")
DATABASE_NAME = os.environ.get("DB_NAME")
SQLALCHEMY_DATABASE_URI = f"postgresql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"
